#!/bin/bash -Eu
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TODO: detect our OS
if [ $(boot2docker status) != 'running' ]; then
  echo 'Starting boot2docker VM...'
  boot2docker up
fi

echo 'Building docker container'
docker build -t stealthly/kafkamanager .

echo 'Starting docker runtime in background'
#docker run --rm -it stealthly/kafkamanager

id=$(docker run -p 9000:9000 -t -d stealthly/kafkamanager)

echo 'Kafka manager started on port 9000'